### PR TITLE
Extra output

### PR DESCRIPTION
**Pull request by VaticanUK**
Hi Bart

New PR for you :)

github is formatting the changes pretty nastily, but I've just added a try/catch around the body comparison.

I just had an issue where my API was returning an error result and it was quite hard to diagnose because the exception logged by com-pact was around failing to case from JObject to JToken deep inside Newtonsoft.Json.

Adding the below quickly exposed the fact that the API was returning an error result with some details around the error rather than the expected body.

Longer term, I might create a PR to add detailed logging about what is going on at each step, with that logging being optionally output via configuration? Normally I'd imagine you'd have it turned off, but if a test starts failing you might turn it on to help diagnose the root cause of the failure?

### CODE REVIEW

**Comment by bartschotten** [comment]
Out of curiosity, can you give me an example that causes this exception? I haven't managed to call Body.Match with any parameters that make this happen.

**Comment by VaticanUK** [comment]
Let me try and remember. We've just started using pact properly rather than just some noddy examples to spike it out, and today I've spent most of the day fixing various issues with the pacts (and the issue with headers in the other PR :))

I *think* the below is an accurate description...

So we had a badly written pact which looked like this:
```
        await provider.addInteraction({
            state: 'form data is stored',
            uponReceiving: 'a form data submission',
            withRequest: {
                method: 'POST',
                path: 'some\path',
            },
            willRespondWith: {
                status: 200,
                body: '',
            },
        });
```

which cause the .NET based API to respond with an error object something like (i don't have an actual example to hand, but you'll get the idea, and I think an HTTP error code rather than 200)
```
{
    "errorMessage": "Unsupported Media Type",
    "someOtherProperty: "some property value"
}
```

The existing logging resulted in a vague error message about "Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken" inside Newtonsoft.Json with the callstack showing it coming from CompareExpectedTokenWithActual in Body, which in turn was called from ProcessToken in Body.

Once I'd added the logging in this PR, the problem was immediately apparent, and was fixed by fixing the pact definition.

Ultimately the "bug" was in our UI where the pacts were defined, but the root cause was obscured because of the exception thrown in com-pact

Changing the pact definition as follows fixed the underlying issue (and then I hit the headers issue :)):
```
        await provider.addInteraction({
        state: 'form data is stored',
            uponReceiving: 'a form data submission',
            withRequest: {
                method: 'POST',
                path: `some\path`,
                headers: {
                    'Content-Type': 'application/json-patch+json',
                },
                body: expectedRequestBody,
            },
            willRespondWith: {
                status: 200,
                headers: {
                    'Content-Type': 'application/json',
                },
                body: expectedResponseBody,
            },
        });
```

**Comment by bartschotten** [comment]
While trying to reproduce this I found another bug. If the response body cannot be deserialized from JSON at all it also throws an exception, but that happens even earlier. I pushed a fix for that to master.

I would really like know what it is that is basically a valid JObject but causes an exception while traversing the tree. That point to an actual issue that I'd like to fix instead of just catching the exception.

**Comment by VaticanUK** [comment]
This: https://stackoverflow.com/questions/49611958/getting-cannot-cast-newtonsoft-json-linq-jobject-to-newtonsoft-json-linq-jtoken

Seems to suggest that you can get that exception if you attempt to treat a object as an array. It could be something along those lines maybe? I'll try and find time tomorrow to reproduce it.

I still think outputting a comparison of the expected and actual body is useful though since it helps find the problem much faster if you can manually compare to see what's different

**Comment by bartschotten** [comment]
There isn't really such a thing as _the_ expected body, since there are also matching rules at play. That's what makes it tricky.

**Comment by VaticanUK** [comment]
Hmm ok.. sorry been a bit swamped the last few days but will hopefully get back to this shortly!

**Comment by VaticanUK** [comment]
Ok, I've worked this through

As previously mentioned, the response coming back from the API is an error message with the structure:
{{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "|27c8b100-4021e724942a52d1."
}}

because the expected body is an empty string, the call to expectedRootToken.ThisTokenAndAllItsDescendents (https://github.com/bartschotten/com-pact/blob/master/ComPact/Models/Body.cs#L29) returns a single token with value "".

matchingRules.Body.Count = 0
matchingRules.Header.Count = 0

In ProcessToken, the token.Type is null (though I think this exception would happen for any "simple" type): https://github.com/bartschotten/com-pact/blob/master/ComPact/Models/Body.cs#L74

So we end up at Line 96 in CompareExpectedTokenWithActual (https://github.com/bartschotten/com-pact/blob/master/ComPact/Models/Body.cs#L96) and the actualToken is a token representing an object, whereas the expectedToken has a type of string.

We then ask for actualToken.Value<string>() which fails because the actualToken is an object.

Perhaps at the start of CompareExpectedTokenWithActual we should compare the types of expectedToken and actualToken? If those types don't match give an error message showing the expectedToken.Value and actualToken.Value?

**Comment by VaticanUK** [comment]
Updated with suggestion based on the above.

**Pull request merged**
